version: '3'

services:
  db:
    image: postgres:15
    container_name: TNotesPostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports:
      - '5555:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: TNotesApp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

    volumes:
      - ./migrations:/app/migrations

volumes:
  postgres_data: