version: '3'

services:
  db:
    image: postgres:15
    container_name: TNotesPostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    environment:
      - POSTGRES_DB=tnotes_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111

  app:
    build: .
    container_name: TNotesApp
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    volumes:
      - ./migrations:/app/migrations

  redis_db:
    image: redis:6.2-alpine
    container_name: TNotesRedis
    restart: always
    ports:
      - '6666:6379'
    environment:
      - REDIS_PASSWORD=222
      - REDIS_PORT=6379
      - REDIS_DATABASES=tnotes_cache
volumes:
  postgres_data: